name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-x86:
    name: x86 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare 3rdparty
        run: git submodule update --init
      - name: Build x86
        run: sh ./build.sh

  build-aarch64:
    name: aarch64 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare 3rdparty
        run: git submodule update --init
      - name: Build aarch64
        run: sh ./build_aarch64.sh
